# Generated by Django 4.2.28 on 2026-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CDF', 'CDF'), ('BIF', 'BIF')], default='BIF', max_length=10),
        ),
    ]
