# Generated by Django 4.2.28 on 2026-02-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shopsettings_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopsettings',
            old_name='shop_name',
            new_name='name',
        ),
    ]
