# Generated by Django 4.2.28 on 2026-02-28 06:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_shop_name_shopsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
