# Generated by Django 4.2.28 on 2026-05-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
