# Generated by Django 4.2.28 on 2026-02-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_saleitem_price_sale_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'En cours'), ('completed', 'Finalisée')], default='draft', max_length=20),
        ),
    ]
