# Generated by Django 4.2.28 on 2026-05-12 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_sale_customer_name_sale_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_restaurant_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('served', 'Servi'), ('paid', 'Payé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='restaurant_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurent.restauranttable'),
        ),
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sales', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
