# Generated by Django 4.2.28 on 2026-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée cuisine'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('served', 'Servie'), ('paid', 'Payée')], default='pending', max_length=20),
        ),
    ]
